FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

# Run uvicorn. 
# Since we are in /backend, 'app.main:app' points to /backend/app/main.py
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]